import { ListOrdered } from "lucide-react";
import type { Metadata } from "next";
import { PageHeader } from "@/components/ui/page-header";
import { EmptyState } from "@/components/ui/empty-state";

export const metadata: Metadata = { title: "Tier List" };

export default function TierListPage() {
  return (
    <div className="mx-auto max-w-7xl space-y-8 px-4 py-12 sm:px-6 lg:px-8">
      <PageHeader
        eyebrow="Ranked meta"
        title="Champion tier list"
        description="Ranked by win rate, pick rate and ban rate for the current patch."
      />
      <EmptyState
        icon={<ListOrdered className="size-8" />}
        title="No snapshot loaded yet"
        description="Tier data is generated by the ingestion pipeline. Once a snapshot exists for this region and patch, rankings appear here."
      />
    </div>
  );
}
