/**
 * Curated lane assignments for the seed dataset.
 *
 * Data Dragon only publishes class tags (Fighter, Mage, ...), which say nothing
 * about which lane a champion actually plays. Without this map the placeholder
 * data puts Azir on bot lane and Lee Sin on top, which makes every role-split
 * page look broken. Real ingestion derives roles from `teamPosition` and
 * ignores this file entirely.
 *
 * Keys are Data Dragon ids. Champions released after this map was written fall
 * back to class-tag weighting, which is imprecise but harmless.
 */
import type { Role } from "../../src/lib/lol/constants";

/** [primary lane, optional secondary lane] */
export const CHAMPION_LANES: Record<string, [Role] | [Role, Role]> = {
  Aatrox: ["TOP"],
  Ahri: ["MIDDLE"],
  Akali: ["MIDDLE", "TOP"],
  Akshan: ["MIDDLE", "TOP"],
  Alistar: ["UTILITY"],
  Ambessa: ["TOP", "MIDDLE"],
  Amumu: ["JUNGLE", "UTILITY"],
  Anivia: ["MIDDLE"],
  Annie: ["MIDDLE", "UTILITY"],
  Aphelios: ["BOTTOM"],
  Ashe: ["BOTTOM", "UTILITY"],
  AurelionSol: ["MIDDLE"],
  Aurora: ["MIDDLE", "TOP"],
  Azir: ["MIDDLE"],
  Bard: ["UTILITY"],
  Belveth: ["JUNGLE"],
  Blitzcrank: ["UTILITY"],
  Brand: ["UTILITY", "MIDDLE"],
  Braum: ["UTILITY"],
  Briar: ["JUNGLE"],
  Caitlyn: ["BOTTOM"],
  Camille: ["TOP"],
  Cassiopeia: ["MIDDLE"],
  Chogath: ["TOP"],
  Corki: ["MIDDLE", "BOTTOM"],
  Darius: ["TOP"],
  Diana: ["JUNGLE", "MIDDLE"],
  DrMundo: ["TOP", "JUNGLE"],
  Draven: ["BOTTOM"],
  Ekko: ["JUNGLE", "MIDDLE"],
  Elise: ["JUNGLE"],
  Evelynn: ["JUNGLE"],
  Ezreal: ["BOTTOM"],
  Fiddlesticks: ["JUNGLE"],
  Fiora: ["TOP"],
  Fizz: ["MIDDLE"],
  Galio: ["MIDDLE", "UTILITY"],
  Gangplank: ["TOP"],
  Garen: ["TOP"],
  Gnar: ["TOP"],
  Gragas: ["JUNGLE", "TOP"],
  Graves: ["JUNGLE"],
  Gwen: ["TOP", "JUNGLE"],
  Hecarim: ["JUNGLE"],
  Heimerdinger: ["MIDDLE", "TOP"],
  Hwei: ["MIDDLE", "UTILITY"],
  Illaoi: ["TOP"],
  Irelia: ["TOP", "MIDDLE"],
  Ivern: ["JUNGLE"],
  Janna: ["UTILITY"],
  JarvanIV: ["JUNGLE"],
  Jax: ["TOP", "JUNGLE"],
  Jayce: ["TOP", "MIDDLE"],
  Jhin: ["BOTTOM"],
  Jinx: ["BOTTOM"],
  KSante: ["TOP"],
  Kaisa: ["BOTTOM"],
  Kalista: ["BOTTOM"],
  Karma: ["UTILITY", "MIDDLE"],
  Karthus: ["JUNGLE", "MIDDLE"],
  Kassadin: ["MIDDLE"],
  Katarina: ["MIDDLE"],
  Kayle: ["TOP", "MIDDLE"],
  Kayn: ["JUNGLE"],
  Kennen: ["TOP"],
  Khazix: ["JUNGLE"],
  Kindred: ["JUNGLE"],
  Kled: ["TOP"],
  KogMaw: ["BOTTOM"],
  Leblanc: ["MIDDLE"],
  LeeSin: ["JUNGLE"],
  Leona: ["UTILITY"],
  Lillia: ["JUNGLE"],
  Lissandra: ["MIDDLE"],
  Lucian: ["BOTTOM", "MIDDLE"],
  Lulu: ["UTILITY"],
  Lux: ["UTILITY", "MIDDLE"],
  Malphite: ["TOP", "UTILITY"],
  Malzahar: ["MIDDLE"],
  Maokai: ["UTILITY", "TOP"],
  MasterYi: ["JUNGLE"],
  Mel: ["MIDDLE", "UTILITY"],
  Milio: ["UTILITY"],
  MissFortune: ["BOTTOM"],
  Mordekaiser: ["TOP"],
  Morgana: ["UTILITY", "MIDDLE"],
  Naafiri: ["MIDDLE", "JUNGLE"],
  Nami: ["UTILITY"],
  Nasus: ["TOP"],
  Nautilus: ["UTILITY"],
  Neeko: ["UTILITY", "MIDDLE"],
  Nidalee: ["JUNGLE"],
  Nilah: ["BOTTOM"],
  Nocturne: ["JUNGLE"],
  Nunu: ["JUNGLE"],
  Olaf: ["TOP", "JUNGLE"],
  Orianna: ["MIDDLE"],
  Ornn: ["TOP"],
  Pantheon: ["UTILITY", "TOP"],
  Poppy: ["JUNGLE", "TOP"],
  Pyke: ["UTILITY"],
  Qiyana: ["MIDDLE"],
  Quinn: ["TOP"],
  Rakan: ["UTILITY"],
  Rammus: ["JUNGLE"],
  RekSai: ["JUNGLE"],
  Rell: ["UTILITY"],
  Renata: ["UTILITY"],
  Renekton: ["TOP"],
  Rengar: ["JUNGLE", "TOP"],
  Riven: ["TOP"],
  Rumble: ["TOP", "MIDDLE"],
  Ryze: ["MIDDLE", "TOP"],
  Samira: ["BOTTOM"],
  Sejuani: ["JUNGLE"],
  Senna: ["UTILITY", "BOTTOM"],
  Seraphine: ["UTILITY", "MIDDLE"],
  Sett: ["TOP", "UTILITY"],
  Shaco: ["JUNGLE", "UTILITY"],
  Shen: ["TOP"],
  Shyvana: ["JUNGLE"],
  Singed: ["TOP"],
  Sion: ["TOP"],
  Sivir: ["BOTTOM"],
  Skarner: ["JUNGLE", "TOP"],
  Smolder: ["BOTTOM", "MIDDLE"],
  Sona: ["UTILITY"],
  Soraka: ["UTILITY"],
  Swain: ["MIDDLE", "UTILITY"],
  Sylas: ["MIDDLE", "TOP"],
  Syndra: ["MIDDLE"],
  TahmKench: ["TOP", "UTILITY"],
  Taliyah: ["JUNGLE", "MIDDLE"],
  Talon: ["MIDDLE", "JUNGLE"],
  Taric: ["UTILITY"],
  Teemo: ["TOP"],
  Thresh: ["UTILITY"],
  Tristana: ["BOTTOM", "MIDDLE"],
  Trundle: ["JUNGLE", "TOP"],
  Tryndamere: ["TOP"],
  TwistedFate: ["MIDDLE"],
  Twitch: ["BOTTOM", "JUNGLE"],
  Udyr: ["JUNGLE", "TOP"],
  Urgot: ["TOP"],
  Varus: ["BOTTOM", "MIDDLE"],
  Vayne: ["BOTTOM", "TOP"],
  Veigar: ["MIDDLE", "BOTTOM"],
  Velkoz: ["MIDDLE", "UTILITY"],
  Vex: ["MIDDLE"],
  Vi: ["JUNGLE"],
  Viego: ["JUNGLE"],
  Viktor: ["MIDDLE"],
  Vladimir: ["MIDDLE", "TOP"],
  Volibear: ["TOP", "JUNGLE"],
  Warwick: ["JUNGLE", "TOP"],
  MonkeyKing: ["JUNGLE", "TOP"],
  Xayah: ["BOTTOM"],
  Xerath: ["MIDDLE", "UTILITY"],
  XinZhao: ["JUNGLE"],
  Yasuo: ["MIDDLE", "TOP"],
  Yone: ["MIDDLE", "TOP"],
  Yorick: ["TOP"],
  Yunara: ["BOTTOM"],
  Yuumi: ["UTILITY"],
  Zac: ["JUNGLE", "TOP"],
  Zed: ["MIDDLE"],
  Zeri: ["BOTTOM"],
  Ziggs: ["MIDDLE", "BOTTOM"],
  Zilean: ["UTILITY", "MIDDLE"],
  Zoe: ["MIDDLE"],
  Zyra: ["UTILITY"],
};
